stages: 
  - deploy

deploy:
  tags:
    - shell
  stage: deploy
  only:
    - master
  script:
    - export MODELS_DIR=/home/gitlab-runner/gensim-data
    - export APP_PORT=80
    - docker-compose -p dev_backend down --rmi local
    - docker-compose -p dev_backend up --build -d
